name = "my-app"
compatibility_date = "2024-08-08"

# [vars]
# MY_VAR = "my-variable"

 [[kv_namespaces]]
binding = "CACHE"
id = "82e1bbc5b8c54daa8a36de1e111d330d"
# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

# [[d1_databases]]
# binding = "DB"
# database_name = "my-database"
# database_id = ""

# [ai]
# binding = "AI"
